name: Go

on:
  pull_request:
    branches: [main]

jobs:
  go-ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          GO_VERSION=`sed -n '3p' go.mod | awk '{print $2}'`
          echo "GO_VERSION=${GO_VERSION}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Format Go application
        run: make format

      - name: Test Go application (unit-tests)
        run: make test

      - name: Build Go application
        run: make build
